### ISSUE TITLE
Placing a bid low maxValuation - after the locktime not being able to withdraw to place a new one with higher maxValuation

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#29]
Example:
* I place a 5 ETH bid with 1000 ETH maxValuation
* the valuation now reaches above and the original bid will not give me any tokeks

If it is within `fullBonusLength` or `partialWithdrawalLength` I can `withdraw` and place a new one.

If it is `withdrawalLockUpLength` then I'm out of luck -  the 5 ETH will remain locked - let's hope I have some liquidity...

### Potential workarounds (long term):
* allow updating existing bid
* allow withdrawing if the valuation is higher than maxValuation
* kick out and  offer automatic  refunds, just like blog #18 

![image](https://user-images.githubusercontent.com/249703/40041932-95141d94-5817-11e8-999b-ef4f4d331a9a.png)

### Because timing is "almost there"
*  explain  in readme:

> if  you provide low  MaxValuation and valuation will become higher, then  you are out  of luck. Smoking skills. Don't print this email.  Consult your doctor.

**Comment by clesaege** [comment]
Well if the valuation goes above it, you will get refunded only at the end. I agree that it would have been better to refund as soon as the "committed amount taking into account max val" is enough, but that would be quite complex to implement. In particular because finding  the "committed amount taking into account max val" takes O(n), so it must be splittable into multiple functions (something like https://github.com/kleros/openiico-contract/blob/master/contracts/IICO.sol#L201).
So we chose not to implement that.

A workarround would be to use a left-sum tree (a tree sorted by max valuation where each node also contains the sum of its left nodes) which would allow finding the current "committed amount taking into account max val" in O(log(n)). But that would rely on an quite exotic data structure and more code, thus lowering security.
